# Generated by Django 3.0.7 on 2020-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='network_traffic',
            field=models.BigIntegerField(default=3221225472),
        ),
        migrations.AlterField(
            model_name='user',
            name='used_traffic',
            field=models.BigIntegerField(default=0),
        ),
    ]
