# Generated by Django 3.0.7 on 2020-06-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200609_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='register_time',
            new_name='signup_time',
        ),
    ]
